class usilParams {
	def dockerRegistryUrl = 'https://dtr.docker.si2m.tec'
	//def dockerRegistryImageBuild='test-store/si2m-npm10-build'
	def dockerRegistryImageNodeBuild='tools-store/usil-nodejs10.13.0-build:1.0.0'
	//def dockerRegistryImageMavenBuild='test-store/maven:3.5.4-jdk-8'
	def dockerRegistryImageMavenBuild = 'tools-store/usil-java.8-maven.3.6:1.0.1'
	// ajout image java 11
	def dockerRegistryImageMavenBuild11='i18fm00/usil-java.11-maven.3.6.3:1.0.1'
	def dockerRegistryImageSBTBuild='tools-store/usil-sbt-jdk8-build:1.3.4'
	def dockerMavenJdk12='tools-store/usil-openjdk12-build:latest'
	def dockerMavenJdk13='tools-store/usil-openjdk13-build:latest'
	def dockerRegistryRepo='repo-store'
	def dockerRegistryRepoProd='app-store'
	def dockerRegistryUser='DockerDTR'
	// def nexusRepoNpm='http://vlionxu001.si2m.tec:8081/nexus/content/groups/public-npm'
	// def nexusRepoNpmPublish='http://vlionxu001.si2m.tec:8081/nexus/content/repositories/Npm-si2m'
	def nexusRepoNpm='http://nexus.si2m.tec/repository/npm-public-group/'
	def nexusRepoNpmPublish='http://nexus.si2m.tec/repository/Npm-si2m/'
	// def nexusRepo='http://vlc3inf013:8081/repository/npm-si2m'
	def nexusRepoMaven=''
	def gitBitbucketUrl='https://bitbucket.org/si2m/'
}
